### ISSUE TITLE
Investigate/fix failing workflow 'Build, Scan / build / Build & Push'

### ISSUE THREAD

**Issue by jburns24** [liatrio/image-builder-aws-terraform#1]
This repo was a modified fork of liatrio/image-builder-azure-terraform. The workflows came from that fork. So it is not known if this workflow will work as is for this repo.

**Comment by densellp** [comment]
@jburns24 So what exactly do you what to test?

**Comment by mcbillings** [comment]
Workflow is  completing successfully now. It was failing for two reasons:

- One of the actions we were using required there to be at lease one tag in our repository.
- The release branch specified in our .releaserc.yaml file was 'main', but we have a branch 'master' instead.
